export const GET_BOOK_LIST_REQUEST = "GET_BOOK_LIST_REQUEST";
export const GET_BOOK_LIST_SUCCESS = "GET_BOOK_LIST_SUCCESS";
export const GET_BOOK_LIST_FAILURE = "GET_BOOK_LIST_FAILURE";


// export const ADD_BOOK_LIST_REQUEST = "ADD_BOOK_LIST_REQUEST";
// export const ADD_BOOK_LIST_SUCCESS = "ADD_BOOK_LIST_SUCCESS";
// export const ADD_BOOK_LIST_FAILURE = "ADD_BOOK_LIST_FAILURE";
